// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLShortener is an autogenerated mock type for the URLShortener type
type URLShortener struct {
	mock.Mock
}

// ResolveOrignalURL provides a mock function with given fields: shortURL
func (_m *URLShortener) ResolveOrignalURL(shortURL string) (string, error) {
	ret := _m.Called(shortURL)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shorten provides a mock function with given fields: orignalURL
func (_m *URLShortener) Shorten(orignalURL string) (string, error) {
	ret := _m.Called(orignalURL)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(orignalURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orignalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
